#!/usr/bin/env ruby
require 'gli'
begin # XXX: Remove this begin/rescue before distributing your app
require 'phaserunner_cli'
rescue LoadError
  STDERR.puts "In development, you need to use `bundle exec bin/phaserunner_cli` to run your app"
  STDERR.puts "At install-time, RubyGems will make sure lib, etc. are in the load path"
  STDERR.puts "Feel free to remove this message from bin/phaserunner_cli now"
  exit 64
end

include GLI::App

program_desc 'Describe your application here'

version PhaserunnerCli::VERSION

subcommand_option_handling :normal
arguments :strict

desc 'Describe some switch here'
switch [:s,:switch]

desc 'Describe some flag here'
default_value 'the default'
arg_name 'The name of the argument'
flag [:f,:flagname]

desc 'Describe read_register here'
arg_name 'Describe arguments to read_register here'
command :read_register do |c|
  c.desc 'Describe a switch to read_register'
  c.switch :s

  c.desc 'Describe a flag to read_register'
  c.default_value 'default'
  c.flag :f
  c.action do |global_options,options,args|

    # Your command logic here
     
    # If you have any errors, just raise them
    # raise "that command made no sense"

    puts "read_register command ran"
  end
end

desc 'Describe read_bulk here'
arg_name 'Describe arguments to read_bulk here'
command :read_bulk do |c|
  c.action do |global_options,options,args|
    puts "read_bulk command ran"
  end
end

pre do |global,command,options,args|
  # Pre logic here
  # Return true to proceed; false to abort and not call the
  # chosen command
  # Use skips_pre before a command to skip this block
  # on that command only
  true
end

post do |global,command,options,args|
  # Post logic here
  # Use skips_post before a command to skip this
  # block on that command only
end

on_error do |exception|
  # Error logic here
  # return false to skip default error handling
  true
end

exit run(ARGV)
